<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TasksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tasks')->insert([
            ['id' => 1, 'name' => 'Создать текст', 'code' => 'make_text'],
            ['id' => 2, 'name' => 'Создать изображение', 'code' => 'make_image'],
            ['id' => 3, 'name' => 'Создать видео', 'code' => 'make_video'],
            ['id' => 4, 'name' => 'Отредактировать изображение', 'code' => 'edit_image'],
            ['id' => 5, 'name' => 'Проанализировать контент', 'code' => 'analyze_content'],
            ['id' => 6, 'name' => 'Улучшить текст', 'code' => 'improve_text'],
            ['id' => 7, 'name' => 'Написать код', 'code' => 'write_code'],
            ['id' => 8, 'name' => 'Поиск', 'code' => 'search'],
            ['id' => 9, 'name' => 'Создать аудио', 'code' => 'make_audio'],
            ['id' => 10, 'name' => 'Создать 3D-объект', 'code' => 'make_3d_object'],
            ['id' => 11, 'name' => 'Создать чат-бота', 'code' => 'make_chatbot'],
            ['id' => 12, 'name' => 'Преобразовать текст в речь', 'code' => 'text_to_speech'],
            ['id' => 13, 'name' => 'Написать статью', 'code' => 'write_article'],
            ['id' => 14, 'name' => 'Создать анимацию', 'code' => 'make_animation'],
            ['id' => 15, 'name' => 'Написать пост', 'code' => 'write_post'],
            ['id' => 16, 'name' => 'Проанализировать изображение', 'code' => 'analyze_image'],
            ['id' => 17, 'name' => 'Улучшить качество изображения', 'code' => 'enhance_image_quality'],
            ['id' => 18, 'name' => 'Резюмировать контент', 'code' => 'summarize_content'],
            ['id' => 19, 'name' => 'Преобразовать речь в текст', 'code' => 'speech_to_text'],
            ['id' => 20, 'name' => 'Написать e-mail', 'code' => 'write_email'],
            ['id' => 21, 'name' => 'Получить аналитику', 'code' => 'get_analytics'],
            ['id' => 22, 'name' => 'Создать контент', 'code' => 'create_content'],
            ['id' => 23, 'name' => 'Deep fake', 'code' => 'deep_fake'],
            ['id' => 24, 'name' => 'Перенести стиль', 'code' => 'transfer_style'],
            ['id' => 25, 'name' => 'Улучшить запрос', 'code' => 'improve_query'],
            ['id' => 26, 'name' => 'Удалить фон', 'code' => 'remove_background'],
            ['id' => 27, 'name' => 'Создать сайт', 'code' => 'make_website'],
            ['id' => 28, 'name' => 'Создать аватар', 'code' => 'make_avatar'],
            ['id' => 29, 'name' => 'Проанализировать документ', 'code' => 'analyze_document'],
            ['id' => 30, 'name' => 'Отредактировать видео', 'code' => 'edit_video'],
            ['id' => 31, 'name' => 'Сгенерировать музыку', 'code' => 'generate_music'],
            ['id' => 32, 'name' => 'Отредактировать изображение по параметрам', 'code' => 'edit_image_by_params'],
            ['id' => 33, 'name' => 'Отредактировать изображение с текстом', 'code' => 'edit_image_with_text'],
            ['id' => 34, 'name' => 'Восстановить изображение', 'code' => 'restore_image'],
            ['id' => 35, 'name' => 'Создать презентацию', 'code' => 'make_presentation'],
            ['id' => 36, 'name' => 'Создать 3D-персонажа', 'code' => 'make_3d_character'],
            ['id' => 37, 'name' => 'Изменить фон', 'code' => 'change_background'],
            ['id' => 38, 'name' => 'Описание товара', 'code' => 'product_description'],
            ['id' => 39, 'name' => 'Создать приложение', 'code' => 'make_app'],
            ['id' => 40, 'name' => 'Создать логотип', 'code' => 'make_logo'],
            ['id' => 41, 'name' => 'Удалить объект', 'code' => 'remove_object'],
            ['id' => 42, 'name' => 'Создать 3D-сцену', 'code' => 'make_3d_scene'],
            ['id' => 43, 'name' => 'Визуализировать данные', 'code' => 'visualize_data'],
            ['id' => 44, 'name' => 'Локализовать', 'code' => 'localize'],
            ['id' => 45, 'name' => 'Проанализировать сайт', 'code' => 'analyze_website'],
            ['id' => 46, 'name' => 'Проанализировать видео', 'code' => 'analyze_video'],
            ['id' => 47, 'name' => 'Проанализировать PDF', 'code' => 'analyze_pdf'],
            ['id' => 48, 'name' => 'Написать поэму', 'code' => 'write_poem'],
            ['id' => 49, 'name' => 'Создать музыку', 'code' => 'make_music'],
            ['id' => 50, 'name' => 'Играть', 'code' => 'play'],
            ['id' => 51, 'name' => 'Отредактировать изображение по референсу', 'code' => 'edit_image_by_reference'],
            ['id' => 52, 'name' => 'Проанализировать аудио', 'code' => 'analyze_audio'],
            ['id' => 53, 'name' => 'Создать портрет', 'code' => 'make_portrait'],
            ['id' => 54, 'name' => 'Описать изображение', 'code' => 'describe_image'],
            ['id' => 55, 'name' => 'Синтезировать голос', 'code' => 'synthesize_voice'],
            ['id' => 56, 'name' => 'Раскрасить', 'code' => 'colorize'],
            ['id' => 57, 'name' => 'Улучшить качество видео', 'code' => 'enhance_video_quality'],
            ['id' => 58, 'name' => 'Отредактировать изображение с наброском', 'code' => 'edit_image_with_sketch'],
            ['id' => 59, 'name' => 'Найти вдохновение', 'code' => 'find_inspiration'],
            ['id' => 60, 'name' => 'Создать текстуру', 'code' => 'make_texture'],
            ['id' => 61, 'name' => 'Создать иконки', 'code' => 'make_icons'],
            ['id' => 62, 'name' => 'Удалить водяной знак', 'code' => 'remove_watermark'],
            ['id' => 63, 'name' => 'Восстановить', 'code' => 'restore'],
            ['id' => 64, 'name' => 'Отследить позу тела', 'code' => 'track_body_pose'],
            ['id' => 65, 'name' => 'Анимировать 3D-персонажа', 'code' => 'animate_3d_character'],
            ['id' => 66, 'name' => 'Распознать текст', 'code' => 'recognize_text'],
            ['id' => 67, 'name' => 'Проверить на плагиат', 'code' => 'check_plagiarism'],
            ['id' => 68, 'name' => 'Применить эффекты к видео', 'code' => 'apply_video_effects'],
            ['id' => 69, 'name' => 'Извлечь голос из аудио', 'code' => 'extract_voice_from_audio'],
            ['id' => 70, 'name' => 'Распознать лицо', 'code' => 'recognize_face'],
            ['id' => 71, 'name' => 'Описать видео', 'code' => 'describe_video'],
            ['id' => 72, 'name' => 'Создать фон', 'code' => 'create_background'],
            ['id' => 73, 'name' => 'Создать эффект slow-mo', 'code' => 'make_slowmo'],
            ['id' => 74, 'name' => 'Создать 3D-видео', 'code' => 'make_3d_video'],
            ['id' => 75, 'name' => 'Применить эффекты к изображению', 'code' => 'apply_image_effects'],
            ['id' => 76, 'name' => 'Монетизировать', 'code' => 'monetize'],
            ['id' => 77, 'name' => 'Синхронизировать движения губ с видео', 'code' => 'sync_lip_movements'],
            ['id' => 78, 'name' => 'Создать запрос', 'code' => 'create_query'],
            ['id' => 79, 'name' => 'Найти референсы', 'code' => 'find_references'],
            ['id' => 80, 'name' => 'Создать концепт', 'code' => 'create_concept'],
            ['id' => 81, 'name' => 'Стилизовать', 'code' => 'stylize'],
            ['id' => 82, 'name' => 'Отредактировать видео по референсу', 'code' => 'edit_video_by_reference'],
            ['id' => 83, 'name' => 'Перекрасить', 'code' => 'repaint'],
            ['id' => 84, 'name' => 'Найти объект', 'code' => 'find_object'],
            ['id' => 85, 'name' => 'Изменить голос', 'code' => 'change_voice'],
            ['id' => 86, 'name' => 'Заменить объект', 'code' => 'replace_object'],
            ['id' => 87, 'name' => 'Поделиться искусством', 'code' => 'share_art'],
            ['id' => 88, 'name' => 'Расширить изображение', 'code' => 'expand_image'],
            ['id' => 89, 'name' => 'Изменить позу тела', 'code' => 'change_body_pose'],
            ['id' => 90, 'name' => 'Интерполяция кадров', 'code' => 'frame_interpolation'],
            ['id' => 91, 'name' => 'Добавить объект', 'code' => 'add_object'],
            ['id' => 92, 'name' => 'Восстановить видео', 'code' => 'restore_video'],
            ['id' => 93, 'name' => 'Анимировать лицо', 'code' => 'animate_face'],
            ['id' => 94, 'name' => 'Убрать шум из аудио', 'code' => 'remove_audio_noise'],
            ['id' => 95, 'name' => 'Создать 3D-текстуру', 'code' => 'make_3d_texture'],
            ['id' => 96, 'name' => 'Создать объёмное видео', 'code' => 'make_volumetric_video'],
            ['id' => 97, 'name' => 'Создать эффект морфинга', 'code' => 'make_morphing_effect'],
            ['id' => 98, 'name' => 'Убрать шум', 'code' => 'remove_noise'],
            ['id' => 99, 'name' => 'Сгенерировать строки', 'code' => 'generate_lines'],
            ['id' => 100, 'name' => 'Анализ данных', 'code' => 'data_analysis'],
            ['id' => 101, 'name' => 'Изменить время суток', 'code' => 'change_time_of_day'],
            ['id' => 102, 'name' => 'Настроить Point Cloud', 'code' => 'adjust_point_cloud'],
            ['id' => 103, 'name' => 'Сегментировать Point Cloud', 'code' => 'segment_point_cloud'],
            ['id' => 104, 'name' => 'Улучшить ночное фото', 'code' => 'enhance_night_photo'],
            ['id' => 105, 'name' => 'Трансформировать визуал', 'code' => 'transform_visual'],
            ['id' => 106, 'name' => 'Удалить фон в видео', 'code' => 'remove_background_in_video'],
            ['id' => 107, 'name' => 'Удалить куски из аудио', 'code' => 'remove_audio_segments'],
            ['id' => 108, 'name' => 'Создать панораму', 'code' => 'make_panorama'],
            ['id' => 109, 'name' => 'Отфильтровать Point Cloud', 'code' => 'filter_point_cloud'],
            ['id' => 110, 'name' => 'Найти похожие 3D', 'code' => 'find_similar_3d'],
            ['id' => 111, 'name' => 'Убрать сжатие', 'code' => 'remove_compression'],
            ['id' => 112, 'name' => 'Стабилизировать видео', 'code' => 'stabilize_video'],
            ['id' => 113, 'name' => 'Создать объёмное изображение', 'code' => 'make_volumetric_image'],
            ['id' => 114, 'name' => 'Создать большее количество точек в Point Cloud', 'code' => 'increase_point_cloud_density'],
            ['id' => 115, 'name' => 'Создать диаграмму', 'code' => 'make_diagram'],
            ['id' => 116, 'name' => 'Уменьшить масштаб изображения', 'code' => 'reduce_image_scale'],
            ['id' => 117, 'name' => 'Создать карту глубины', 'code' => 'create_depth_map'],
            ['id' => 118, 'name' => 'Создать набросок', 'code' => 'make_sketch'],
            ['id' => 119, 'name' => 'Создать субтитры', 'code' => 'create_subtitles'],
            ['id' => 120, 'name' => 'Создать таблицу', 'code' => 'create_table'],
            ['id' => 121, 'name' => 'Сопоставить аудио с визуал', 'code' => 'match_audio_with_visual'],
            ['id' => 122, 'name' => 'Разработка веб-приложений', 'code' => 'web_app_development'],
            ['id' => 123, 'name' => 'Клонирование голоса', 'code' => 'voice_cloning'],
            ['id' => 124, 'name' => 'Автоматизация задач для бизнеса', 'code' => 'business_task_automation'],
            ['id' => 125, 'name' => 'Общение', 'code' => 'communication'],
            ['id' => 126, 'name' => 'Найти текстуру', 'code' => 'find_texture'],
            ['id' => 127, 'name' => 'Маскироваться', 'code' => 'camouflage'],
            ['id' => 128, 'name' => 'Редактирование видео', 'code' => 'video_editing'],
            ['id' => 129, 'name' => 'Применить объекты к видео', 'code' => 'apply_objects_to_video'],
            ['id' => 130, 'name' => 'Управление задачами', 'code' => 'task_management'],
            ['id' => 131, 'name' => 'Перефразирование', 'code' => 'paraphrasing'],
            ['id' => 132, 'name' => 'Перевод видео', 'code' => 'translate_video'],
            ['id' => 133, 'name' => 'Перевести текст', 'code' => 'translate_text'],
            ['id' => 134, 'name' => 'Создать озвучку', 'code' => 'create_voiceover'],
            ['id' => 135, 'name' => 'Создать перевод', 'code' => 'create_translation'],
            ['id' => 136, 'name' => 'Создание моделей', 'code' => 'model_creation'],
            ['id' => 137, 'name' => 'Создать реальную физическую анимацию', 'code' => 'create_realistic_physics_animation'],
            ['id' => 138, 'name' => 'Заменить небо', 'code' => 'replace_sky'],
            ['id' => 139, 'name' => 'Добавить водяной знак', 'code' => 'add_watermark'],
            ['id' => 140, 'name' => 'Добавить взаимодействие в 3D-сцену', 'code' => 'add_interaction_to_3d_scene'],
            ['id' => 141, 'name' => 'Деформировать 3D-объект', 'code' => 'deform_3d_object'],
            ['id' => 142, 'name' => 'Текст в код', 'code' => 'text_to_code'],
            ['id' => 143, 'name' => 'Генерация отчетов', 'code' => 'generate_reports'],
            ['id' => 144, 'name' => 'Генерация каверов', 'code' => 'generate_covers'],
            ['id' => 145, 'name' => 'Выровнять голос', 'code' => 'normalize_voice'],
            ['id' => 146, 'name' => 'Анализ сообщений', 'code' => 'message_analysis'],
        ]);
    }
}
