<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransformationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('transformations')->insert([
            ['id' => 1, 'name' => 'Текст в текст', 'code' => 'text_to_text'],
            ['id' => 2, 'name' => 'Текст в изображение', 'code' => 'text_to_image'],
            ['id' => 3, 'name' => 'Изображение в изображение', 'code' => 'image_to_image'],
            ['id' => 4, 'name' => 'Текст в аудио', 'code' => 'text_to_audio'],
            ['id' => 5, 'name' => 'Данные в текст', 'code' => 'data_to_text'],
            ['id' => 6, 'name' => 'Текст в видео', 'code' => 'text_to_video'],
            ['id' => 7, 'name' => 'Видео в видео', 'code' => 'video_to_video'],
            ['id' => 8, 'name' => 'Текст в код', 'code' => 'text_to_code_duplicate'],
            ['id' => 9, 'name' => 'Изображение в видео', 'code' => 'image_to_video'],
            ['id' => 10, 'name' => 'Изображение в 3D', 'code' => 'image_to_3d'],
            ['id' => 11, 'name' => 'Аудио в текст', 'code' => 'audio_to_text'],
            ['id' => 12, 'name' => 'Изображение в текст', 'code' => 'image_to_text'],
            ['id' => 13, 'name' => 'Видео в текст', 'code' => 'video_to_text'],
            ['id' => 14, 'name' => 'Аудио в аудио', 'code' => 'audio_to_audio'],
            ['id' => 15, 'name' => 'Данные в данные', 'code' => 'data_to_data'],
            ['id' => 16, 'name' => 'Текст в данные', 'code' => 'text_to_data'],
            ['id' => 17, 'name' => 'Текст в 3D', 'code' => 'text_to_3d'],
            ['id' => 18, 'name' => 'Изображение-текст-изображение', 'code' => 'image_text_image'],
            ['id' => 19, 'name' => 'Текст в сайт', 'code' => 'text_to_website'],
            ['id' => 20, 'name' => 'Код в код', 'code' => 'code_to_code'],
            ['id' => 21, 'name' => '3D в 3D', 'code' => '3d_to_3d'],
            ['id' => 22, 'name' => 'Набросок в изображение', 'code' => 'sketch_to_image'],
            ['id' => 23, 'name' => 'Видео в 3D', 'code' => 'video_to_3d'],
            ['id' => 24, 'name' => 'Текст в приложение', 'code' => 'text_to_app'],
            ['id' => 25, 'name' => 'Данные в диаграмму', 'code' => 'data_to_diagram'],
            ['id' => 26, 'name' => 'Изображение в данные', 'code' => 'image_to_data'],
            ['id' => 27, 'name' => 'Аудио в видео', 'code' => 'audio_to_video'],
            ['id' => 28, 'name' => 'Видео в аудио', 'code' => 'video_to_audio'],
            ['id' => 29, 'name' => 'Сайт в данные', 'code' => 'website_to_data'],
            ['id' => 30, 'name' => 'Текст в SVG', 'code' => 'text_to_svg'],
            ['id' => 31, 'name' => 'Код в текст', 'code' => 'code_to_text'],
            ['id' => 32, 'name' => 'Текст в текстуру', 'code' => 'text_to_texture'],
            ['id' => 33, 'name' => 'Игра', 'code' => 'game'],
            ['id' => 34, 'name' => 'Изображение в аудио', 'code' => 'image_to_audio'],
            ['id' => 35, 'name' => '3D в изображение', 'code' => '3d_to_image'],
            ['id' => 36, 'name' => 'Текст в панораму', 'code' => 'text_to_panorama'],
            ['id' => 37, 'name' => 'Текст в презентацию', 'code' => 'text_to_presentation'],
            ['id' => 38, 'name' => 'Набросок в 3D', 'code' => 'sketch_to_3d'],
            ['id' => 39, 'name' => 'Аудио в 3D', 'code' => 'audio_to_3d'],
            ['id' => 40, 'name' => 'Изображение в анимацию', 'code' => 'image_to_animation'],
            ['id' => 41, 'name' => 'Набросок в видео', 'code' => 'sketch_to_video'],
            ['id' => 42, 'name' => '3D+текст в 3D', 'code' => '3d_text_to_3d'],
            ['id' => 43, 'name' => 'SVG в 3D', 'code' => 'svg_to_3d'],
            ['id' => 44, 'name' => 'Текст в анимацию', 'code' => 'text_to_animation'],
            ['id' => 45, 'name' => 'Сайт в приложение', 'code' => 'website_to_app'],
            ['id' => 46, 'name' => 'Данные в изображение', 'code' => 'data_to_image'],
            ['id' => 47, 'name' => 'Аудио в изображение', 'code' => 'audio_to_image'],
            ['id' => 48, 'name' => 'Задачи в автоматизацию', 'code' => 'tasks_to_automation'],
            ['id' => 49, 'name' => 'Набросок в SVG', 'code' => 'sketch_to_svg'],
            ['id' => 50, 'name' => 'Текст в музыку', 'code' => 'text_to_music'],
            ['id' => 51, 'name' => 'Текст в иллюстрацию', 'code' => 'text_to_illustration'],
            ['id' => 52, 'name' => 'Текст в игру', 'code' => 'text_to_game'],
            ['id' => 53, 'name' => 'Данные в код', 'code' => 'data_to_code'],
            ['id' => 54, 'name' => 'Текст в графический материал', 'code' => 'text_to_graphic'],
            ['id' => 55, 'name' => 'Текст в голос', 'code' => 'text_to_voice'],
            ['id' => 56, 'name' => 'SVG в SVG', 'code' => 'svg_to_svg'],
            ['id' => 57, 'name' => 'Голос в аудио', 'code' => 'voice_to_audio'],
            ['id' => 58, 'name' => 'Документ в документ', 'code' => 'document_to_document'],
            ['id' => 59, 'name' => 'Текст в речь', 'code' => 'text_to_speech_duplicate'],
            ['id' => 60, 'name' => 'Данные в отчеты', 'code' => 'data_to_reports'],
            ['id' => 61, 'name' => 'Данные в анализ', 'code' => 'data_to_analysis'],
            ['id' => 62, 'name' => '3D-текст-3D', 'code' => '3d_text_3d'],
            ['id' => 63, 'name' => 'Редактирование музыки', 'code' => 'music_editing'],
            ['id' => 64, 'name' => 'Написать текст', 'code' => 'write_text'],
            ['id' => 65, 'name' => 'Написать код', 'code' => 'write_code_duplicate'],
            ['id' => 66, 'name' => 'Текст в комикс', 'code' => 'text_to_comic'],
            ['id' => 67, 'name' => 'Документ в текст', 'code' => 'document_to_text'],
            ['id' => 68, 'name' => 'Текст в тест', 'code' => 'text_to_test'],
            ['id' => 69, 'name' => 'Текст в чат-бот', 'code' => 'text_to_chatbot'],
            ['id' => 70, 'name' => 'Автоматизация таргетинга', 'code' => 'targeting_automation'],
            ['id' => 71, 'name' => 'Управление переводом', 'code' => 'translation_management'],
            ['id' => 72, 'name' => 'Чат-бот', 'code' => 'chatbot'],
            ['id' => 73, 'name' => 'Текст в помощника', 'code' => 'text_to_assistant'],
            ['id' => 74, 'name' => 'Текст в перевод', 'code' => 'text_to_translation'],
            ['id' => 75, 'name' => 'Автоматизация таркетинга', 'code' => 'targeting_automation_typo'],
            ['id' => 76, 'name' => 'Код в автоматизацию', 'code' => 'code_to_automation'],
            ['id' => 77, 'name' => 'Анализ информации', 'code' => 'information_analysis'],
            ['id' => 78, 'name' => 'Текст в иллюстрацию', 'code' => 'text_to_illustration_duplicate'],
            ['id' => 79, 'name' => 'Анализ информации', 'code' => 'information_analysis_duplicate'],
            ['id' => 80, 'name' => 'Текст в графиеский материал', 'code' => 'text_to_graphical_material'],
            ['id' => 81, 'name' => 'Задачи в календарь', 'code' => 'tasks_to_calendar'],
            ['id' => 82, 'name' => 'Голос в текст', 'code' => 'voice_to_text'],
            ['id' => 83, 'name' => 'Данные в автоматизацию', 'code' => 'data_to_automation'],
            ['id' => 84, 'name' => 'Результаты поиска в модель', 'code' => 'search_results_to_model'],
            ['id' => 85, 'name' => 'Результаты веб-поиска в модель', 'code' => 'web_search_to_model'],
            ['id' => 86, 'name' => 'Разработка', 'code' => 'development'],
            ['id' => 87, 'name' => 'Программирование', 'code' => 'programming'],
            ['id' => 88, 'name' => 'Повышение эффективности работы', 'code' => 'efficiency_improvement'],
            ['id' => 89, 'name' => 'Оптимизация рекламы', 'code' => 'advertising_optimization'],
        ]);
    }
}
